"""use datetime for timestamps

Revision ID: ab24d44c8e26
Revises: 5e172e60e85f
Create Date: 2026-05-29 11:19:30.839172

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "ab24d44c8e26"
down_revision: Union[str, Sequence[str], None] = "5e172e60e85f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
